### ISSUE TITLE
MacOS Open File Limit - Error: ENFILE: file table overflow - open files: cannot modify limit: Invalid argument

### ISSUE THREAD

**Issue by MarkPieszak** [mgechev/dotfiles#1]
These might be helpful for others here as well, sometimes these issues come up when developing with {N} (NativeScript) for example.

Sometimes you can get:

```bash
$ bash: ulimit: open files: cannot modify limit: Invalid argument
```

or

```bash
Error: ENFILE: file table overflow
```

---
These bashes could be useful for others:

```bash
$ echo kern.maxfiles=65536 | sudo tee -a /etc/sysctl.conf
$ echo kern.maxfilesperproc=65536 | sudo tee -a /etc/sysctl.conf
$ sudo sysctl -w kern.maxfiles=65536
$ sudo sysctl -w kern.maxfilesperproc=65536
$ ulimit -n 65536 65536    
```

Article: http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit

Just an idea, figured I'd leave this here just in case :)

**Comment by mgechev** [comment]
Hey Mark, thanks for giving my dotfiles a try :-)

I'll take a look at this.

**Comment by mgechev** [comment]
Looks like I forgot to look at it. Closing the issue since it's most likely no longer relevant. Sorry for this.
